# Generated by Django 5.2.12 on 2026-03-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_mandante'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
