# Generated by Django 5.2.12 on 2026-03-30 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_imagenes_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='date_started',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
