# Generated by Django 5.2.12 on 2026-03-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandantes', '0002_remove_contacto_mandante_id_contacto_mandante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
