# Generated by Django 5.2.12 on 2026-03-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandantes', '0003_alter_contacto_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
