# Generated by Django 5.2.12 on 2026-04-03 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0005_proyecto_date_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coeficiente_Cruce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coeficiente', models.FloatField()),
                ('tipo_transporte', models.CharField(max_length=50)),
                ('nomenclatura', models.CharField(max_length=10)),
                ('is_standard', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_dia', models.CharField(choices=[('laboral', 'Día Laboral'), ('sabado', 'Sábado'), ('domingo', 'Domingo/Festivo')], default='laboral', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calles', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Calle',
                'verbose_name_plural': 'Calles',
                'unique_together': {('numero', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=10)),
                ('interseccion', models.CharField(blank=True, max_length=200, null=True)),
                ('plano', models.URLField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('calle_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodos_calle_1', to='red_vial.calle')),
                ('calle_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodos_calle_2', to='red_vial.calle')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='proyectos.proyecto')),
            ],
            options={
                'unique_together': {('numero', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='Arco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('longitud', models.FloatField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcos', to='proyectos.proyecto')),
                ('nodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcos_entrada', to='red_vial.nodo')),
                ('nodo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcos_salida', to='red_vial.nodo')),
            ],
            options={
                'unique_together': {('nodo_origen', 'nodo_destino', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='NodoMovimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_prioridad', models.CharField(choices=[('P', 'Prioritario'), ('S', 'Secundario')], max_length=1)),
                ('regulacion', models.CharField(blank=True, choices=[('Pare', 'Pare'), ('Ceda', 'Ceda el paso'), ('Semaforo', 'Semáforo'), ('Libre', 'Libre')], max_length=20, null=True)),
                ('interseccion_valor', models.FloatField(blank=True, null=True)),
                ('numero_pistas', models.FloatField(blank=True, null=True)),
                ('velocidad_inicial', models.FloatField(blank=True, null=True)),
                ('flujo_total', models.FloatField(blank=True, null=True)),
                ('velocidad_modelo', models.FloatField(blank=True, null=True)),
                ('flujo', models.IntegerField(blank=True, null=True)),
                ('arco_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='red_vial.arco')),
                ('arco_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='red_vial.arco')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='red_vial.movimiento')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_config', to='red_vial.nodo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos_movimientos', to='proyectos.proyecto')),
            ],
            options={
                'unique_together': {('nodo', 'movimiento', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='FlujoMovimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hora', models.TimeField()),
                ('flujo_veh_hora', models.FloatField(blank=True, null=True, verbose_name='Flujo (veh/h)')),
                ('flujo_veq_15min', models.FloatField(blank=True, null=True, verbose_name='VEQ/15min')),
                ('flujo_veq_hora', models.FloatField(blank=True, null=True, verbose_name='VEQ/h')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos_movimiento', to='proyectos.proyecto')),
                ('nodo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos', to='red_vial.nodomovimiento')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos_movimiento', to='red_vial.periodo')),
            ],
            options={
                'ordering': ['hora'],
                'unique_together': {('proyecto', 'nodo_movimiento', 'periodo', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='ConteoVehicular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hora', models.TimeField()),
                ('vl', models.FloatField(blank=True, null=True, verbose_name='VL')),
                ('txc', models.FloatField(blank=True, null=True, verbose_name='TXC')),
                ('txb', models.FloatField(blank=True, null=True, verbose_name='TXB')),
                ('c_2e', models.FloatField(blank=True, null=True, verbose_name='C 2E')),
                ('c_mas_2e', models.FloatField(blank=True, null=True, verbose_name='C+2E')),
                ('peaton', models.FloatField(blank=True, null=True, verbose_name='Peat')),
                ('ciclista', models.FloatField(blank=True, null=True, verbose_name='Cicl')),
                ('moto', models.FloatField(blank=True, null=True, verbose_name='Moto')),
                ('vehiculos_equivalentes', models.FloatField(blank=True, null=True, verbose_name='VEQ')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos_vehiculares', to='proyectos.proyecto')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='red_vial.nodo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='red_vial.periodo')),
            ],
            options={
                'ordering': ['hora'],
                'unique_together': {('proyecto', 'nodo', 'periodo', 'hora')},
            },
        ),
    ]
