# Generated by Django 5.2.12 on 2026-04-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodo",
            name="is_pc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nodo",
            name="numero_pc",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nodo",
            name="numero",
            field=models.IntegerField(),
        ),
    ]
