# Generated by Django 5.2.12 on 2026-04-07 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


def limpiar_nodo_movimientos(apps, schema_editor):
    NodoMovimiento = apps.get_model("red_vial", "NodoMovimiento")
    NodoMovimiento.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0002_nodo_is_pc_nodo_numero_pc_alter_nodo_numero"),
    ]

    operations = [
        # migrations.RunPython(limpiar_nodo_movimientos),
        migrations.CreateModel(
            name="Regulacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="nodomovimiento",
            name="movimiento",
            field=models.CharField(
                blank=True,
                choices=[("Directo", "Dir"), ("Derecha", "Der"), ("Izquierda", "Izq")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nodomovimiento",
            name="regulacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regulaciones_movimiento",
                to="red_vial.regulacion",
            ),
        ),
        migrations.DeleteModel(
            name="Movimiento",
        ),
    ]
