# Generated by Django 5.2.12 on 2026-04-19 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectos", "0005_proyecto_date_started"),
        ("red_vial", "0003_regulacion_alter_nodomovimiento_movimiento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PuntoControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movimiento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("12", "Nodo 1 → Nodo 2"),
                            ("13", "Nodo 1 → Nodo 3"),
                            ("14", "Nodo 1 → Nodo 4"),
                            ("21", "Nodo 2 → Nodo 1"),
                            ("23", "Nodo 2 → Nodo 3"),
                            ("24", "Nodo 2 → Nodo 4"),
                            ("31", "Nodo 3 → Nodo 1"),
                            ("32", "Nodo 3 → Nodo 2"),
                            ("34", "Nodo 3 → Nodo 4"),
                            ("41", "Nodo 4 → Nodo 1"),
                            ("42", "Nodo 4 → Nodo 2"),
                            ("43", "Nodo 4 → Nodo 3"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "viraje",
                    models.CharField(
                        blank=True,
                        choices=[("DIR", "Directo"), ("DER", "Derecha"), ("IZQ", "Izquierda")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("is_prioritario", models.BooleanField(default=False)),
                ("numero_pistas", models.FloatField(blank=True, null=True)),
                ("flujo", models.IntegerField(blank=True, null=True)),
                ("interseccion_valor", models.FloatField(blank=True, null=True)),
                ("velocidad_inicial", models.FloatField(blank=True, null=True)),
                ("flujo_total", models.FloatField(blank=True, null=True)),
                ("velocidad_modelo", models.FloatField(blank=True, null=True)),
                (
                    "arco_entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pc_input",
                        to="red_vial.arco",
                    ),
                ),
                (
                    "arco_salida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pc_output",
                        to="red_vial.arco",
                    ),
                ),
                (
                    "nodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pc_nodo",
                        to="red_vial.nodo",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntos_control",
                        to="proyectos.proyecto",
                    ),
                ),
                (
                    "regulacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pc_regulacion",
                        to="red_vial.regulacion",
                    ),
                ),
            ],
            options={
                "unique_together": {("nodo", "movimiento", "proyecto")},
            },
        ),
    ]
