# Generated by Django 5.2.12 on 2026-05-28 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectos", "0005_proyecto_date_started"),
        ("red_vial", "0004_puntocontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodo",
            name="proyecto",
            field=models.ForeignKey(
                default="779f0f79-4b6e-4d9c-aa3d-e75f15efe0cd",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periodos",
                to="proyectos.proyecto",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="periodo",
            unique_together={("proyecto", "codigo")},
        ),
        migrations.RemoveField(
            model_name="puntocontrol",
            name="flujo",
        ),
        migrations.RemoveField(
            model_name="puntocontrol",
            name="flujo_total",
        ),
        migrations.RemoveField(
            model_name="puntocontrol",
            name="interseccion_valor",
        ),
        migrations.RemoveField(
            model_name="puntocontrol",
            name="velocidad_inicial",
        ),
        migrations.RemoveField(
            model_name="puntocontrol",
            name="velocidad_modelo",
        ),
        migrations.AddField(
            model_name="periodo",
            name="es_laboral",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="periodo",
            name="hora_fin",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="periodo",
            name="hora_inicio",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="puntocontrol",
            name="nombre",
            field=models.CharField(default="init", max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conteovehicular",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traficos",
                to="red_vial.periodo",
            ),
        ),
        migrations.AlterField(
            model_name="periodo",
            name="codigo",
            field=models.CharField(
                choices=[
                    ("PM-L", "Mañana laboral"),
                    ("PN-L", "Mediodía laboral"),
                    ("PT-L", "Tarde laboral"),
                    ("PE-L", "Noche laboral"),
                    ("PM-S", "Mañana sábado"),
                    ("PN-S", "Mediodía sábado"),
                    ("PT-S", "Tarde sábado"),
                    ("PE-S", "Noche sábado"),
                    ("PM-F", "Mañana no laboral"),
                    ("PN-F", "Mediodía no laboral"),
                    ("PT-F", "Tarde no laboral"),
                    ("PE-F", "Noche no laboral"),
                ],
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="puntocontrol",
            name="movimiento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("12", "Nodo 1 → Nodo 2"),
                    ("13", "Nodo 1 → Nodo 3"),
                    ("14", "Nodo 1 → Nodo 4"),
                    ("15", "Nodo 1 → Nodo 5"),
                    ("16", "Nodo 1 → Nodo 6"),
                    ("21", "Nodo 2 → Nodo 1"),
                    ("23", "Nodo 2 → Nodo 3"),
                    ("24", "Nodo 2 → Nodo 4"),
                    ("25", "Nodo 2 → Nodo 5"),
                    ("26", "Nodo 2 → Nodo 6"),
                    ("31", "Nodo 3 → Nodo 1"),
                    ("32", "Nodo 3 → Nodo 2"),
                    ("34", "Nodo 3 → Nodo 4"),
                    ("35", "Nodo 3 → Nodo 5"),
                    ("36", "Nodo 3 → Nodo 6"),
                    ("41", "Nodo 4 → Nodo 1"),
                    ("42", "Nodo 4 → Nodo 2"),
                    ("43", "Nodo 4 → Nodo 3"),
                    ("45", "Nodo 4 → Nodo 5"),
                    ("46", "Nodo 4 → Nodo 6"),
                    ("51", "Nodo 5 → Nodo 1"),
                    ("52", "Nodo 5 → Nodo 2"),
                    ("53", "Nodo 5 → Nodo 3"),
                    ("54", "Nodo 5 → Nodo 4"),
                    ("56", "Nodo 5 → Nodo 6"),
                    ("61", "Nodo 6 → Nodo 1"),
                    ("62", "Nodo 6 → Nodo 2"),
                    ("63", "Nodo 6 → Nodo 3"),
                    ("64", "Nodo 6 → Nodo 4"),
                    ("65", "Nodo 6 → Nodo 5"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="puntocontrol",
            name="regulacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pc_regulacion",
                to="red_vial.regulacion",
            ),
        ),
        migrations.RemoveField(
            model_name="periodo",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="periodo",
            name="tipo_dia",
        ),
        migrations.CreateModel(
            name="Periodizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hora", models.TimeField(help_text="Hora de inicio del intervalo de 15 min")),
                ("vl", models.PositiveIntegerField(default=0, verbose_name="Vehículo liviano")),
                ("txc", models.PositiveIntegerField(default=0, verbose_name="Taxi colectivo")),
                ("txb", models.PositiveIntegerField(default=0, verbose_name="Taxi básico")),
                ("c2e", models.PositiveIntegerField(default=0, verbose_name="Camión 2 ejes")),
                ("c_mas2e", models.PositiveIntegerField(default=0, verbose_name="Camión +2 ejes")),
                ("peat", models.PositiveIntegerField(default=0, verbose_name="Peatón")),
                ("cicl", models.PositiveIntegerField(default=0, verbose_name="Ciclista")),
                ("moto", models.PositiveIntegerField(default=0, verbose_name="Motocicleta")),
                (
                    "pc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodizaciones",
                        to="red_vial.puntocontrol",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodizaciones",
                        to="red_vial.periodo",
                    ),
                ),
            ],
            options={
                "ordering": ["periodo", "hora"],
                "unique_together": {("pc", "periodo", "hora")},
            },
        ),
        migrations.CreateModel(
            name="ResumenFlujo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flujo",
                    models.IntegerField(
                        blank=True, help_text="Flujo calculado (mín. 10 veh/h)", null=True
                    ),
                ),
                ("flujo_total", models.FloatField(blank=True, null=True)),
                ("interseccion_valor", models.FloatField(blank=True, null=True)),
                ("velocidad_inicial", models.FloatField(blank=True, null=True)),
                ("velocidad_modelo", models.FloatField(blank=True, null=True)),
                (
                    "pc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumenes",
                        to="red_vial.puntocontrol",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumenes",
                        to="red_vial.periodo",
                    ),
                ),
            ],
            options={
                "unique_together": {("pc", "periodo")},
            },
        ),
    ]
