# Generated by Django 5.2.12 on 2026-05-28 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectos", "0005_proyecto_date_started"),
        ("red_vial", "0005_alter_periodo_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="periodizacion",
            options={},
        ),
        migrations.AddField(
            model_name="periodizacion",
            name="ftot",
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="c2e",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="c_mas2e",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="cicl",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="hora",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="moto",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="pc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conteos",
                to="red_vial.puntocontrol",
            ),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="peat",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conteos",
                to="red_vial.periodo",
            ),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="txb",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="txc",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="periodizacion",
            name="vl",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CoeficienteCruce",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nomenclatura", models.CharField(max_length=10)),
                ("tipo_transporte", models.CharField(max_length=50)),
                ("coeficiente", models.FloatField()),
                ("is_standard", models.BooleanField(default=False)),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coeficientes",
                        to="proyectos.proyecto",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nomenclatura", "proyecto"), name="unique_coef_por_proyecto"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("proyecto__isnull", True)),
                        fields=("nomenclatura",),
                        name="unique_coef_estandar",
                    ),
                ],
            },
        ),
    ]
