# Generated by Django 5.2.12 on 2026-05-28 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0006_alter_periodizacion_options_periodizacion_ftot_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="puntocontrol",
            options={"verbose_name": "Punto_Control", "verbose_name_plural": "Puntos_Control"},
        ),
    ]
