# Generated by Django 5.2.12 on 2026-06-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0007_alter_puntocontrol_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodo",
            name="is_pc",
        ),
        migrations.RemoveField(
            model_name="puntocontrol",
            name="nombre",
        ),
        migrations.AlterField(
            model_name="nodo",
            name="numero_pc",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Número del PC asociado (ej: 3 → PC-03). Null si no es PC.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="puntocontrol",
            name="movimiento",
            field=models.CharField(
                choices=[
                    ("12", "Nodo 1 → Nodo 2"),
                    ("13", "Nodo 1 → Nodo 3"),
                    ("14", "Nodo 1 → Nodo 4"),
                    ("15", "Nodo 1 → Nodo 5"),
                    ("16", "Nodo 1 → Nodo 6"),
                    ("21", "Nodo 2 → Nodo 1"),
                    ("23", "Nodo 2 → Nodo 3"),
                    ("24", "Nodo 2 → Nodo 4"),
                    ("25", "Nodo 2 → Nodo 5"),
                    ("26", "Nodo 2 → Nodo 6"),
                    ("31", "Nodo 3 → Nodo 1"),
                    ("32", "Nodo 3 → Nodo 2"),
                    ("34", "Nodo 3 → Nodo 4"),
                    ("35", "Nodo 3 → Nodo 5"),
                    ("36", "Nodo 3 → Nodo 6"),
                    ("41", "Nodo 4 → Nodo 1"),
                    ("42", "Nodo 4 → Nodo 2"),
                    ("43", "Nodo 4 → Nodo 3"),
                    ("45", "Nodo 4 → Nodo 5"),
                    ("46", "Nodo 4 → Nodo 6"),
                    ("51", "Nodo 5 → Nodo 1"),
                    ("52", "Nodo 5 → Nodo 2"),
                    ("53", "Nodo 5 → Nodo 3"),
                    ("54", "Nodo 5 → Nodo 4"),
                    ("56", "Nodo 5 → Nodo 6"),
                    ("61", "Nodo 6 → Nodo 1"),
                    ("62", "Nodo 6 → Nodo 2"),
                    ("63", "Nodo 6 → Nodo 3"),
                    ("64", "Nodo 6 → Nodo 4"),
                    ("65", "Nodo 6 → Nodo 5"),
                ],
                default="12",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
