# Generated by Django 5.2.12 on 2026-06-02 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0008_remove_nodo_is_pc_remove_puntocontrol_nombre_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="periodizacion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="periodizacion",
            name="fecha",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name="periodizacion",
            unique_together={("fecha", "pc", "periodo", "hora")},
        ),
    ]
