# Generated by Django 5.2.12 on 2026-06-03 16:38

from django.db import migrations, models
from django.db.models import Sum, Avg, Count


def seed_resumen_flujo(apps, schema_editor):
    ResumenFlujo = apps.get_model("red_vial", "ResumenFlujo")
    Periodizacion = apps.get_model("red_vial", "Periodizacion")

    aggs = Periodizacion.objects.values("pc", "periodo").annotate(
        flujo_total=Sum("ftot"),
        promedio=Avg("ftot"),
        num_registros=Count("id"),
    )
    objs = []
    for agg in aggs:
        ftot = agg["flujo_total"] or 0
        objs.append(
            ResumenFlujo(
                pc_id=agg["pc"],
                periodo_id=agg["periodo"],
                flujo_total=round(ftot, 2),
                promedio=round(agg["promedio"], 2) if agg["promedio"] else 0,
                num_registros=agg["num_registros"],
                flujo=max(10, round(ftot)),
            )
        )
    ResumenFlujo.objects.bulk_create(objs, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0012_uppercase_nomenclatura_coef"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumenflujo",
            name="num_registros",
            field=models.IntegerField(
                blank=True, help_text="Número de registros de Periodización agregados", null=True
            ),
        ),
        migrations.AddField(
            model_name="resumenflujo",
            name="promedio",
            field=models.FloatField(
                blank=True, help_text="Promedio de ftot por registro de 15 min", null=True
            ),
        ),
        migrations.RunPython(seed_resumen_flujo, migrations.RunPython.noop),
    ]
