# Generated by Django 5.2.12 on 2026-06-04 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyectos", "0005_proyecto_date_started"),
        ("red_vial", "0014_remove_legacy_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionTransyt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ciclo",
                    models.PositiveIntegerField(
                        default=60, help_text="Tiempo de ciclo en segundos"
                    ),
                ),
                (
                    "W",
                    models.FloatField(
                        default=10.0, help_text="Costo por hora de demora ($/hr-veh) — Tarjeta 1"
                    ),
                ),
                (
                    "K",
                    models.FloatField(
                        default=0.5, help_text="Costo por detención ($/det) — Tarjeta 1"
                    ),
                ),
                (
                    "perdida_inicial",
                    models.FloatField(
                        default=2.0, help_text="Pérdida inicial en segundos — Tarjeta 1"
                    ),
                ),
                (
                    "ganancia_final",
                    models.FloatField(
                        default=1.0, help_text="Ganancia final en segundos — Tarjeta 1"
                    ),
                ),
                (
                    "proyecto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_transyt",
                        to="proyectos.proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración TRANSYT",
                "verbose_name_plural": "Configuraciones TRANSYT",
            },
        ),
        migrations.CreateModel(
            name="ParametroArco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flujo_saturacion",
                    models.FloatField(
                        default=1800.0,
                        help_text="Flujo de saturación en ADE/hr verde — Tarjeta 30/31",
                    ),
                ),
                (
                    "ponderador_demora",
                    models.FloatField(
                        default=1.0, help_text="Ponderador w_i para costo de demora — Tarjeta 30/31"
                    ),
                ),
                (
                    "ponderador_detencion",
                    models.FloatField(
                        default=1.0,
                        help_text="Ponderador k_i para costo de detención — Tarjeta 30/31",
                    ),
                ),
                (
                    "capacidad_cola",
                    models.FloatField(
                        blank=True,
                        help_text="Capacidad física de cola en ADE — Tarjeta 38",
                        null=True,
                    ),
                ),
                (
                    "tiene_tarjeta_38",
                    models.BooleanField(
                        default=False,
                        help_text="Si tiene Tarjeta 38, el exceso de cola se suma al IR",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametros_arco",
                        to="proyectos.proyecto",
                    ),
                ),
                (
                    "punto_control",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametro_arco",
                        to="red_vial.puntocontrol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parámetro de Arco",
                "verbose_name_plural": "Parámetros de Arco (Tarjetas 30/31/38)",
            },
        ),
        migrations.CreateModel(
            name="FaseSemaforica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fase_numero",
                    models.PositiveSmallIntegerField(help_text="Número de fase semafórica"),
                ),
                ("verde_inicio", models.FloatField(help_text="Inicio del verde en segundos")),
                ("verde_fin", models.FloatField(help_text="Fin del verde en segundos")),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fases_semaforicas",
                        to="proyectos.proyecto",
                    ),
                ),
                (
                    "punto_control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fases_semaforicas",
                        to="red_vial.puntocontrol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fase Semafórica",
                "verbose_name_plural": "Fases Semafóricas",
                "unique_together": {("punto_control", "fase_numero")},
            },
        ),
    ]
