# Generated by Django 5.2.12 on 2026-06-10 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0015_configuraciontransyt_parametroarco_fasesemaforica"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="periodizacion",
            unique_together={("fecha", "pc", "hora")},
        ),
    ]
