# Generated by Django 5.2.12 on 2026-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0016_fix_periodizacion_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="periodizacion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="periodizacion",
            name="mov",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="periodizacion",
            unique_together={("fecha", "pc", "mov", "hora")},
        ),
    ]
