# Generated by Django 5.2.12 on 2026-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0017_add_mov_to_periodizacion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="periodizacion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="periodizacion",
            name="pc_mov",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: _populate_pc_mov(apps, schema_editor),
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="periodizacion",
            name="mov",
        ),
        migrations.AlterUniqueTogether(
            name="periodizacion",
            unique_together={("fecha", "pc", "hora")},
        ),
    ]


def _populate_pc_mov(apps, schema_editor):
    Periodizacion = apps.get_model("red_vial", "Periodizacion")
    db_alias = schema_editor.connection.alias
    for p in Periodizacion.objects.using(db_alias).select_related("pc__nodo").all():
        p.pc_mov = f"PC-{p.pc.nodo.numero_pc:02d}-{p.mov}"
        p.save(update_fields=["pc_mov"])
