# Generated by Django 5.2.12 on 2026-06-11 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0018_add_pc_mov_to_periodizacion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="periodizacion",
            unique_together={("fecha", "pc_mov", "hora")},
        ),
    ]
