# Generated by Django 5.2.12 on 2026-06-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0019_alter_periodizacion_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="puntocontrol",
            name="interseccion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="puntocontrol",
            name="vel_ini",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puntocontrol",
            name="vel_mod",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
