# Generated by Django 5.2.12 on 2026-07-06 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("red_vial", "0020_puntocontrol_interseccion_puntocontrol_vel_ini_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="periodizacion",
            unique_together={("fecha", "pc", "pc_mov", "hora")},
        ),
    ]
